### ISSUE TITLE
Gitea integration has a Bug

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#14]
Investigating 

Version < v1.3.0 
```
[1] listRepos: gitea
[1] Response {
[1]   size: 0,
[1]   timeout: 0,
[1]   data: null,
[1]   error: FetchError: invalid json response body at http://localhost:3000/api/v1undefined reason: Unexpected token < in JSON at position 0
[1]       at /kubero/node_modules/node-fetch/lib/index.js:273:32
[1]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]       at async/kubero-dev/kubero/node_modules/gitea-js/dist/index.js:145:44 {
[1]     type: 'invalid-json'
[1]   },
[1]   [Symbol(Body internals)]: {
[1]     body: PassThrough {
[1]       _readableState: [ReadableState],
[1]       _events: [Object: null prototype],
[1]       _eventsCount: 4,
[1]       _maxListeners: undefined,
[1]       _writableState: [WritableState],
[1]       allowHalfOpen: true,
[1]       [Symbol(kCapture)]: false,
[1]       [Symbol(kCallback)]: null
[1]     },
[1]     disturbed: true,
[1]     error: null
[1]   },
[1]   [Symbol(Response internals)]: {
[1]     url: 'http://localhost:3000/api/v1undefined',
[1]     status: 404,
[1]     statusText: 'Not Found',
[1]     headers: Headers { [Symbol(map)]: [Object: null prototype] },
[1]     counter: 0
[1]   }
[1] }
```

**Comment by mms-gianni** [comment]
only listing failed. Fixed in Version 1.3.0
