### ISSUE TITLE
make app dir writable

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#232]
There are cases where we need a writable app directory (it is in running container read only) There is a switch for the root docker container, but this does not affects the mounted `/app` dir

**Comment by kdiogenes** [comment]
I'm unable to run a Rails application due this:
```
*  Max threads: 5
*  Environment: development
*          PID: 7
Rails Error: Unable to access log file. Please ensure that /app/log/development.log exists and is writable (i.e. make it writable for user and group: chmod 0664 /app/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
* Listening on http://0.0.0.0:80
bundler: failed to load command: puma (/app/bundle/bin/puma)
/app/bundle/gems/puma-5.6.7/lib/puma/launcher.rb:259:in `write': Read-only file system @ rb_sysopen - tmp/pids/server.pid (Errno::EROFS)
	from /app/bundle/gems/puma-5.6.7/lib/puma/launcher.rb:259:in `write_pid'
	from /app/bundle/gems/puma-5.6.7/lib/puma/launcher.rb:112:in `write_state'
	from /app/bundle/gems/puma-5.6.7/lib/puma/single.rb:48:in `run'
	from /app/bundle/gems/puma-5.6.7/lib/puma/launcher.rb:193:in `run'
	from /app/bundle/gems/puma-5.6.7/lib/puma/cli.rb:81:in `run'
	from /app/bundle/gems/puma-5.6.7/bin/puma:10:in `<top (required)>'
	from /app/bundle/bin/puma:25:in `load'
	from /app/bundle/bin/puma:25:in `<top (required)>'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/cli/exec.rb:58:in `load'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/cli/exec.rb:23:in `run'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/cli.rb:492:in `exec'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/cli.rb:34:in `dispatch'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/cli.rb:28:in `start'
	from /app/bundle/gems/bundler-2.4.18/exe/bundle:37:in `block in <top (required)>'
	from /app/bundle/gems/bundler-2.4.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /app/bundle/gems/bundler-2.4.18/exe/bundle:29:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
```

Is there any workaround?

**Comment by mms-gianni** [comment]
Not yet. But let's prioritize this. I think this is a quick fix.

**Comment by mms-gianni** [comment]
Well, I obviously need to improve my docs. 

I've added this feature more than a year ago 

https://github.com/kubero-dev/kubero-operator/blob/main/helm-charts/kuberoapp/templates/deployment-web.yaml#L142 

So editing this in your `kuberoapp` CRD is the workaround. 

I'll add this to the UI.

**Comment by mms-gianni** [comment]
Here is an example how to add it. 

https://github.com/kubero-dev/kubero/blob/f3ecdab71d88791341561fa97324a73879ba0d56/services/laravel/app.yaml#L17
