### ISSUE TITLE
Kubero is crashing when pipeline has no buildpack configuration

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#240]
```
[1] /Users/carafagi/workdir/kubero-dev/kubero/dist/kubero.js:208
[1]                 pipeline.spec.buildpack.fetch.securityContext = config_1.Buildpack.SetSecurityContext(pipeline.spec.buildpack.fetch.securityContext);
[1]                                         ^
[1]
[1] TypeError: Cannot read properties of undefined (reading 'fetch')
[1]     at Kubero.<anonymous> (/Users/carafagi/workdir/kubero-dev/kubero/dist/kubero.js:208:41)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/Users/carafagi/workdir/kubero-dev/kubero/dist/kubero.js:28:58)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]
```

**Comment by mms-gianni** [comment]
Fixed here : 
https://github.com/kubero-dev/kubero/commit/49bd74c75ad7f56ff1c618e8440e1af7459e7b76 

released in v1.11.3
